package com.example.ui.screens

import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.DevelopedByFooter
import com.example.ui.components.GeneratedByFooter
import com.example.ui.components.StatCard
import com.example.ui.theme.SalesGreen
import com.example.ui.theme.ExpenseRed
import com.example.ui.theme.ProfitBlue
import com.example.ui.theme.PendingOrange
import com.example.ui.viewmodel.RuvionViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportsScreen(viewModel: RuvionViewModel) {
    val context = LocalContext.current
    val transactions by viewModel.allTransactions.collectAsState()
    val expenses by viewModel.allExpenses.collectAsState()
    val activeRole by viewModel.activeRole.collectAsState()

    var selectedFilterTab by remember { mutableStateOf("MONTHLY") } // DAILY, WEEKLY, MONTHLY, YEARLY

    val sales = transactions.filter { it.type == "SALE" }
    val purchases = transactions.filter { it.type == "PURCHASE" }

    val totalSales = sales.sumOf { it.totalAmount }
    val totalPurchases = purchases.sumOf { it.totalAmount }
    val totalExpenses = expenses.sumOf { it.amount }

    // GST computations
    val salesTax = sales.sumOf { it.tax }
    val cgst = salesTax / 2.0
    val sgst = salesTax / 2.0

    val purchaseTax = purchases.sumOf { it.tax }

    // Net GST liability
    val netGstPayable = (salesTax - purchaseTax).coerceAtLeast(0.0)

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Title Header
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text(
                    text = "Accounting & GST Portal",
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Black)
                )
                Text(
                    text = "Real-time compliance bookkeeping",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f)
                )
            }

            IconButton(
                onClick = {
                    Toast.makeText(context, "GST Ledger PDF downloaded! Generated by Ruvion.", Toast.LENGTH_LONG).show()
                }
            ) {
                Icon(Icons.Default.Download, "Download Report", tint = MaterialTheme.colorScheme.primary)
            }
        }

        // Filters tab row
        TabRow(
            selectedTabIndex = when (selectedFilterTab) {
                "DAILY" -> 0
                "WEEKLY" -> 1
                "MONTHLY" -> 2
                else -> 3
            },
            modifier = Modifier.fillMaxWidth()
        ) {
            listOf("DAILY", "WEEKLY", "MONTHLY", "YEARLY").forEach { tab ->
                Tab(
                    selected = selectedFilterTab == tab,
                    onClick = { selectedFilterTab = tab },
                    text = { Text(tab) }
                )
            }
        }

        if (activeRole != "Staff") {
            // General Sales and Tax Summary
            Text(
                text = "Tax Matrix Breakdown",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold)
            )

            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                StatCard(
                    title = "Total CGST Received",
                    value = "₹${"%,.2f".format(cgst)}",
                    subtitle = "Central GST (6% / 9% / 18%)",
                    icon = Icons.Default.ReceiptLong,
                    color = ProfitBlue,
                    modifier = Modifier.weight(1f)
                )
                StatCard(
                    title = "Total SGST Received",
                    value = "₹${"%,.2f".format(sgst)}",
                    subtitle = "State GST (6% / 9% / 18%)",
                    icon = Icons.Default.ReceiptLong,
                    color = SalesGreen,
                    modifier = Modifier.weight(1f)
                )
            }

            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                StatCard(
                    title = "Purchase Input Tax",
                    value = "₹${"%,.2f".format(purchaseTax)}",
                    subtitle = "GST paid on stocks",
                    icon = Icons.Default.AssignmentReturned,
                    color = PendingOrange,
                    modifier = Modifier.weight(1f)
                )
                StatCard(
                    title = "Net GST Payable",
                    value = "₹${"%,.2f".format(netGstPayable)}",
                    subtitle = "Tax Liability (Output - Input)",
                    icon = Icons.Default.Gavel,
                    color = ExpenseRed,
                    modifier = Modifier.weight(1f)
                )
            }

            // P&L Balance Ledger Card
            Card(
                shape = RoundedCornerShape(24.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(20.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text(
                        text = "Income & Expense Ledger",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold)
                    )
                    HorizontalDivider()

                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Gross Sales Bookings", style = MaterialTheme.typography.bodyMedium)
                        Text("₹${"%,.2f".format(totalSales)}", style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold, color = SalesGreen))
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Gross Purchase Bookings", style = MaterialTheme.typography.bodyMedium)
                        Text("₹${"%,.2f".format(totalPurchases)}", style = MaterialTheme.typography.bodyMedium.copy(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f)))
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Operational Overheads (Expenses)", style = MaterialTheme.typography.bodyMedium)
                        Text("₹${"%,.2f".format(totalExpenses)}", style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold, color = ExpenseRed))
                    }

                    HorizontalDivider()

                    val netPnL = totalSales - totalPurchases - totalExpenses
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("NET P&L PERFORMANCE", style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold))
                        Text(
                            text = "${if (netPnL >= 0) "Profit: ₹" else "Loss: -₹"}${"%,.2f".format(kotlin.math.abs(netPnL))}",
                            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Black, color = if (netPnL >= 0) SalesGreen else ExpenseRed)
                        )
                    }
                }
            }

            // Export Actions Trigger Bar
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Button(
                    onClick = {
                        Toast.makeText(context, "PDF Report exported!\nFooter: Generated by Ruvion | Developed by Rahul Edition", Toast.LENGTH_LONG).show()
                    },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Icon(Icons.Default.PictureAsPdf, null)
                    Spacer(modifier = Modifier.width(6.dp))
                    Text("Export PDF Report")
                }

                Button(
                    onClick = {
                        Toast.makeText(context, "Excel sheet compiled for Rahul Edition's audit!", Toast.LENGTH_LONG).show()
                    },
                    modifier = Modifier.weight(1f),
                    colors = ButtonDefaults.buttonColors(containerColor = SalesGreen),
                    shape = RoundedCornerShape(14.dp)
                ) {
                    Icon(Icons.Default.GridOn, null)
                    Spacer(modifier = Modifier.width(6.dp))
                    Text("Export Excel File")
                }
            }
        } else {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.error.copy(alpha = 0.05f)),
                shape = RoundedCornerShape(16.dp)
            ) {
                Row(
                    modifier = Modifier.padding(16.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Icon(Icons.Default.Lock, "Lock", tint = ExpenseRed)
                    Text(
                        text = "Access Denied: Financial and compliance tax statements are locked for Staff role.",
                        style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Medium),
                        color = ExpenseRed
                    )
                }
            }
        }

        Spacer(modifier = Modifier.height(16.dp))
        GeneratedByFooter()
        DevelopedByFooter()
    }
}
